mkdir include
copy src\include\srm.h include
copy src\include\srm_types.h include
copy src\include\srm_stds.h include
copy src\include\srm_default.h include
copy src\include\srm_struct_util.h include
copy src\include\srm_print.h include
copy src\include\srm_util.h include
copy src\include\srm_valid.h include
copy src\include\srm_BaseMapProjection.h include
copy src\include\srm_BaseSRF.h include
copy src\include\srm_BaseSRF2D.h include
copy src\include\srm_BaseSRF3D.h include
copy src\include\srm_BaseSRFwithEllipsoidalHeight.h include
copy src\include\srm_BaseSRFwithTangentPlaneSurface.h include
copy src\include\srm_Celestiocentric.h include
copy src\include\srm_Celestiodetic.h include
copy src\include\srm_Celestiomagnetic.h include
copy src\include\srm_Coordinate2D.h include
copy src\include\srm_Coordinate3D.h include
copy src\include\srm_CreateSRFSetMember.h include
copy src\include\srm_CreateStandardSRF.h include
copy src\include\srm_Direction.h include
copy src\include\srm_EquatorialInertial.h include
copy src\include\srm_EquidistantCylindrical.h include
copy src\include\srm_HeliosphericAriesEcliptic.h include
copy src\include\srm_HeliosphericEarthEcliptic.h include
copy src\include\srm_HeliosphericEarthEquatorial.h include
copy src\include\srm_LambertConformalConic.h include
copy src\include\srm_LocalSpaceAzimuthal.h include
copy src\include\srm_LocalSpacePolar.h include
copy src\include\srm_LocalSpaceRectangular2D.h include
copy src\include\srm_LocalSpaceRectangular3D.h include
copy src\include\srm_LocalTangentSpaceAzimuthalSpherical.h include
copy src\include\srm_LocalTangentSpaceCylindrical.h include
copy src\include\srm_LocalTangentSpaceEuclidean.h include
copy src\include\srm_LococentricEuclidean3D.h include
copy src\include\srm_Mercator.h include
copy src\include\srm_ObliqueMercatorSpherical.h include
copy src\include\srm_Orientation.h include
copy src\include\srm_Planetodetic.h include
copy src\include\srm_PolarStereographic.h include
copy src\include\srm_QueryORMSupport.h include
copy src\include\srm_QuerySRFTSupport.h include
copy src\include\srm_SolarEcliptic.h include
copy src\include\srm_SolarEquatorial.h include
copy src\include\srm_SolarMagneticDipole.h include
copy src\include\srm_SolarMagneticEcliptic.h include
copy src\include\srm_SurfaceCoordinate.h include
copy src\include\srm_TransverseMercator.h include
