/*
 *  Copyright (c) 2006 Accent Geographic. All rights reserved.
 *  See the license file for licensing information.
 *  Created: Wed Jul 26 23:47:08 2006
 *
 *  DO NOT EDIT THIS FILE! (Autogenerated)
 */

// SEDRIS C++ SDK Release 4.1.4 - July 1, 2011

/*
 *                             NOTICE
 * 
 * This software is provided openly and freely for use in representing and
 * interchanging environmental data & databases.
 * 
 * This software was developed for use by the United States Government with
 * unlimited rights.  The software was developed under contract
 * DASG60-02-D-0006 TO-193 by Science Applications International Corporation.
 * The software is unclassified and is deemed as Distribution A, approved
 * for Public Release.
 * 
 * Use by others is permitted only upon the ACCEPTANCE OF THE TERMS AND
 * CONDITIONS, AS STIPULATED UNDER THE FOLLOWING PROVISIONS:
 * 
 *    1. Recipient may make unlimited copies of this software and give
 *       copies to other persons or entities as long as the copies contain
 *       this NOTICE, and as long as the same copyright notices that
 *       appear on, or in, this software remain.
 * 
 *    2. Trademarks. All trademarks belong to their respective trademark
 *       holders.  Third-Party applications/software/information are
 *       copyrighted by their respective owners.
 * 
 *    3. Recipient agrees to forfeit all intellectual property and
 *       ownership rights for any version created from the modification
 *       or adaptation of this software, including versions created from
 *       the translation and/or reverse engineering of the software design.
 * 
 *    4. Transfer.  Recipient may not sell, rent, lease, or sublicense
 *       this software.  Recipient may, however enable another person
 *       or entity the rights to use this software, provided that this
 *       AGREEMENT and NOTICE is furnished along with the software and
 *       /or software system utilizing this software.
 * 
 *       All revisions, modifications, created by the Recipient, to this
 *       software and/or related technical data shall be forwarded by the
 *       Recipient to the Government at the following address:
 * 
 *         SMDC
 *         Attention SEDRIS (TO193) TPOC
 *         P.O. Box 1500
 *         Huntsville, AL  35807-3801
 * 
 *         or via electronic mail to:  se-mgmt@sedris.org
 * 
 *    5. No Warranty. This software is being delivered to you AS IS
 *       and there is no warranty, EXPRESS or IMPLIED, as to its use
 *       or performance.
 * 
 *       The RECIPIENT ASSUMES ALL RISKS, KNOWN AND UNKNOWN, OF USING
 *       THIS SOFTWARE.  The DEVELOPER EXPRESSLY DISCLAIMS, and the
 *       RECIPIENT WAIVES, ANY and ALL PERFORMANCE OR RESULTS YOU MAY
 *       OBTAIN BY USING THIS SOFTWARE OR DOCUMENTATION.  THERE IS
 *       NO WARRANTY, EXPRESS OR, IMPLIED, AS TO NON-INFRINGEMENT OF
 *       THIRD PARTY RIGHTS, MERCHANTABILITY, OR FITNESS FOR ANY
 *       PARTICULAR PURPOSE.  IN NO EVENT WILL THE DEVELOPER, THE
 *       UNITED STATES GOVERNMENT OR ANYONE ELSE ASSOCIATED WITH THE
 *       DEVELOPMENT OF THIS SOFTWARE BE HELD LIABLE FOR ANY CONSEQUENTIAL,
 *       INCIDENTAL OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS
 *       OR LOST SAVINGS WHATSOEVER.
 */

/** @file seDRMDataTable.h
@author Warren Macchi (Accent Geographic)
@brief Accessors to the seDRMDataTable (51) class.
*/

#ifndef _seDRMDataTable_h
#define _seDRMDataTable_h

#include "seDRMBase.h"

namespace sedris {

/** seDRMDataTable wraps the DRM <a href="../drm/classes/DataTable.htm">&lt;Data_Table&gt;</a> abstract class.
@note This is an ABSTRACT DRM class.

@author Warren Macchi
@version Revision: 1.8
@see seDRMBase
*/
class EXPORT_DLL seDRMDataTable : public seDRMBase
{
public:

    /// Default constructor
    seDRMDataTable() {}

    /// Constructor for seDRM... class conversions
    seDRMDataTable( const seObject &other ) : seDRMBase(other) {}

    // No fields

    /** Set Data Table data.
       See the seHelperDataTable class for an easier interface for accessing
       data table data.

       The @p tpd_count parameter indicates the number of entries in the
       @p dt_data array.

       The @p dt_data array points to an array of Data Table Data structures.
       Each structure entry in this array contains the index of the &lt;Table
       Property Description&gt; the user is accessing the data for
       (<b>element_index</b> field), and the number of cells being accessed
       (<b>data_count</b> field). Note that the value of the <b>data_count</b>
       field must match the actual number of cells to be accessed by this method,
       defined by the extents if @p extents was provided, or by the full extents
       of the table data otherwise.

       @warning Interval and string-based type data storage is currently not
            implemented.
       @warning Once you use putDataTableData() you should not change the
            &lt;Data Table&gt; definition (such as changing the axis count or
            the property types). This is because the API cannot reformat a data
            type storage once the data structures have been allocated. If you
            need to change the &lt;Data Table&gt; definition you must delete
            the &lt;Data Table&gt; object and recreate it.

       @note The user is responsible for allocating/deallocating the data memory.
       @note The pointer type of each SE_Data_Table_Data structure must
            match the type specified in the corresponding &lt;Table Property
            Description&gt;, and the pointer to the actual data must be non-NULL,
            or an exception will occur.
       @see seHelperDataTable
    */
    virtual void putDataTableData( SE_Integer_Positive tpd_count,
                        const SE_Data_Table_Data dt_data[],
                        const SE_Data_Table_Sub_Extent *extents = NULL );

    /** Get Data Table data.
       See the seHelperDataTable class for an easier interface for accessing
       data table data.

       The @p tpd_count parameter indicates the number of entries in the
       @p dt_data array.

       The @p dt_data array points to an array of Data Table Data structures.
       Each structure entry in this array contains the index of the &lt;Table
       Property Description&gt; the user is accessing the data for
       (<b>element_index</b> field), and the number of cells being accessed
       (<b>data_count</b> field). Note that the value of the <b>data_count</b>
       field must match the actual number of cells to be accessed by this method,
       defined by the extents if @p extents was provided, or by the full extents
       of the table data otherwise.

       @note The user is responsible for allocating/deallocating the data memory.
       @note The pointer type of each SE_Data_Table_Data structure must
            match the type specified in the corresponding &lt;Table Property
            Description&gt;, and the pointer to the actual data must be non-NULL,
            or an exception will occur.
       @see seHelperDataTable
    */
    virtual void getDataTableData( SE_Integer_Positive tpd_count,
                        const SE_Data_Table_Data dt_data[],
                        const SE_Data_Table_Sub_Extent *extents = NULL );

    /** Gets the DRM class type this object can reference (mostly internal use).
        @warning Don't confuse with getDRMClass(), which is dependent on the
            actual type held by this DRM class object reference (especially
            because this is an abstract DRM class).
        @return SE_CLS_DRM_DATA_TABLE
    */
    virtual SE_DRM_Class getClassType() const
    {
        return SE_CLS_DRM_DATA_TABLE;
    }

};

} // namespace sedris

#endif // _seDRMDataTable_h
