/*
 *  Copyright (c) 2006 Accent Geographic. All rights reserved.
 *  See the license file for licensing information.
 *  Created: Wed Jul 26 23:47:08 2006
 *
 *  DO NOT EDIT THIS FILE! (Autogenerated)
 */

// SEDRIS C++ SDK Release 4.1.4 - July 1, 2011

/*
 *                             NOTICE
 * 
 * This software is provided openly and freely for use in representing and
 * interchanging environmental data & databases.
 * 
 * This software was developed for use by the United States Government with
 * unlimited rights.  The software was developed under contract
 * DASG60-02-D-0006 TO-193 by Science Applications International Corporation.
 * The software is unclassified and is deemed as Distribution A, approved
 * for Public Release.
 * 
 * Use by others is permitted only upon the ACCEPTANCE OF THE TERMS AND
 * CONDITIONS, AS STIPULATED UNDER THE FOLLOWING PROVISIONS:
 * 
 *    1. Recipient may make unlimited copies of this software and give
 *       copies to other persons or entities as long as the copies contain
 *       this NOTICE, and as long as the same copyright notices that
 *       appear on, or in, this software remain.
 * 
 *    2. Trademarks. All trademarks belong to their respective trademark
 *       holders.  Third-Party applications/software/information are
 *       copyrighted by their respective owners.
 * 
 *    3. Recipient agrees to forfeit all intellectual property and
 *       ownership rights for any version created from the modification
 *       or adaptation of this software, including versions created from
 *       the translation and/or reverse engineering of the software design.
 * 
 *    4. Transfer.  Recipient may not sell, rent, lease, or sublicense
 *       this software.  Recipient may, however enable another person
 *       or entity the rights to use this software, provided that this
 *       AGREEMENT and NOTICE is furnished along with the software and
 *       /or software system utilizing this software.
 * 
 *       All revisions, modifications, created by the Recipient, to this
 *       software and/or related technical data shall be forwarded by the
 *       Recipient to the Government at the following address:
 * 
 *         SMDC
 *         Attention SEDRIS (TO193) TPOC
 *         P.O. Box 1500
 *         Huntsville, AL  35807-3801
 * 
 *         or via electronic mail to:  se-mgmt@sedris.org
 * 
 *    5. No Warranty. This software is being delivered to you AS IS
 *       and there is no warranty, EXPRESS or IMPLIED, as to its use
 *       or performance.
 * 
 *       The RECIPIENT ASSUMES ALL RISKS, KNOWN AND UNKNOWN, OF USING
 *       THIS SOFTWARE.  The DEVELOPER EXPRESSLY DISCLAIMS, and the
 *       RECIPIENT WAIVES, ANY and ALL PERFORMANCE OR RESULTS YOU MAY
 *       OBTAIN BY USING THIS SOFTWARE OR DOCUMENTATION.  THERE IS
 *       NO WARRANTY, EXPRESS OR, IMPLIED, AS TO NON-INFRINGEMENT OF
 *       THIRD PARTY RIGHTS, MERCHANTABILITY, OR FITNESS FOR ANY
 *       PARTICULAR PURPOSE.  IN NO EVENT WILL THE DEVELOPER, THE
 *       UNITED STATES GOVERNMENT OR ANYONE ELSE ASSOCIATED WITH THE
 *       DEVELOPMENT OF THIS SOFTWARE BE HELD LIABLE FOR ANY CONSEQUENTIAL,
 *       INCIDENTAL OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS
 *       OR LOST SAVINGS WHATSOEVER.
 */

/** @file seDRMBasePositionalLight.h
@author Warren Macchi (Accent Geographic)
@brief Accessors to the seDRMBasePositionalLight (17) class.
*/

#ifndef _seDRMBasePositionalLight_h
#define _seDRMBasePositionalLight_h

#include "seDRMLightSource.h"

namespace sedris {

/** seDRMBasePositionalLight wraps the DRM <a href="../drm/classes/BasePositionalLight.htm">&lt;Base_Positional_Light&gt;</a> abstract class.
@note This is an ABSTRACT DRM class.

@author Warren Macchi
@version Revision: 1.8
@see seDRMLightSource
*/
class seDRMBasePositionalLight : public seDRMLightSource
{
public:

    /// Default constructor
    seDRMBasePositionalLight() {}

    /// Constructor for seDRM... class conversions
    seDRMBasePositionalLight( const seObject &other ) : seDRMLightSource(other) {}

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#apply_to_children">apply_to_children</a>
    SE_Boolean get_apply_to_children()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, apply_to_children);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#apply_to_children">apply_to_children</a>
    void set_apply_to_children( SE_Boolean apply_to_children )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, apply_to_children, apply_to_children);
    }

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#override_positional_lights">override_positional_lights</a>
    SE_Boolean get_override_positional_lights()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, override_positional_lights);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#override_positional_lights">override_positional_lights</a>
    void set_override_positional_lights( SE_Boolean override_positional_lights )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, override_positional_lights, override_positional_lights);
    }

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#override_infinite_lights">override_infinite_lights</a>
    SE_Boolean get_override_infinite_lights()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, override_infinite_lights);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#override_infinite_lights">override_infinite_lights</a>
    void set_override_infinite_lights( SE_Boolean override_infinite_lights )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, override_infinite_lights, override_infinite_lights);
    }

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#active_light_value">active_light_value</a>
    SE_Boolean get_active_light_value()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, active_light_value);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#active_light_value">active_light_value</a>
    void set_active_light_value( SE_Boolean active_light_value )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, active_light_value, active_light_value);
    }

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#radius">radius</a>
    SE_Float get_radius()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, radius);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#radius">radius</a>
    void set_radius( SE_Float radius )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, radius, radius);
    }

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#constant_attenuation_factor">constant_attenuation_factor</a>
    SE_Long_Float get_constant_attenuation_factor()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, constant_attenuation_factor);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#constant_attenuation_factor">constant_attenuation_factor</a>
    void set_constant_attenuation_factor( SE_Long_Float constant_attenuation_factor )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, constant_attenuation_factor, constant_attenuation_factor);
    }

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#linear_attenuation_factor">linear_attenuation_factor</a>
    SE_Long_Float get_linear_attenuation_factor()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, linear_attenuation_factor);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#linear_attenuation_factor">linear_attenuation_factor</a>
    void set_linear_attenuation_factor( SE_Long_Float linear_attenuation_factor )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, linear_attenuation_factor, linear_attenuation_factor);
    }

    /// Get field <a href="../drm/classes/BasePositionalLight.htm#quadratic_attenuation_factor">quadratic_attenuation_factor</a>
    SE_Long_Float get_quadratic_attenuation_factor()
    {
        DRMBASE_RET_FIELDS(Base_Positional_Light, quadratic_attenuation_factor);
    }

    /// Set field <a href="../drm/classes/BasePositionalLight.htm#quadratic_attenuation_factor">quadratic_attenuation_factor</a>
    void set_quadratic_attenuation_factor( SE_Long_Float quadratic_attenuation_factor )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Base_Positional_Light, quadratic_attenuation_factor, quadratic_attenuation_factor);
    }

    /** Gets the DRM class type this object can reference (mostly internal use).
        @warning Don't confuse with getDRMClass(), which is dependent on the
            actual type held by this DRM class object reference (especially
            because this is an abstract DRM class).
        @return SE_CLS_DRM_BASE_POSITIONAL_LIGHT
    */
    virtual SE_DRM_Class getClassType() const
    {
        return SE_CLS_DRM_BASE_POSITIONAL_LIGHT;
    }

};

} // namespace sedris

#endif // _seDRMBasePositionalLight_h
