/*
 *  Copyright (c) 2006 Accent Geographic. All rights reserved.
 *  See the license file for licensing information.
 *  Created: Wed Jul 26 23:47:08 2006
 *
 *  DO NOT EDIT THIS FILE! (Autogenerated)
 */

// SEDRIS C++ SDK Release 4.1.4 - July 1, 2011

/*
 *                             NOTICE
 * 
 * This software is provided openly and freely for use in representing and
 * interchanging environmental data & databases.
 * 
 * This software was developed for use by the United States Government with
 * unlimited rights.  The software was developed under contract
 * DASG60-02-D-0006 TO-193 by Science Applications International Corporation.
 * The software is unclassified and is deemed as Distribution A, approved
 * for Public Release.
 * 
 * Use by others is permitted only upon the ACCEPTANCE OF THE TERMS AND
 * CONDITIONS, AS STIPULATED UNDER THE FOLLOWING PROVISIONS:
 * 
 *    1. Recipient may make unlimited copies of this software and give
 *       copies to other persons or entities as long as the copies contain
 *       this NOTICE, and as long as the same copyright notices that
 *       appear on, or in, this software remain.
 * 
 *    2. Trademarks. All trademarks belong to their respective trademark
 *       holders.  Third-Party applications/software/information are
 *       copyrighted by their respective owners.
 * 
 *    3. Recipient agrees to forfeit all intellectual property and
 *       ownership rights for any version created from the modification
 *       or adaptation of this software, including versions created from
 *       the translation and/or reverse engineering of the software design.
 * 
 *    4. Transfer.  Recipient may not sell, rent, lease, or sublicense
 *       this software.  Recipient may, however enable another person
 *       or entity the rights to use this software, provided that this
 *       AGREEMENT and NOTICE is furnished along with the software and
 *       /or software system utilizing this software.
 * 
 *       All revisions, modifications, created by the Recipient, to this
 *       software and/or related technical data shall be forwarded by the
 *       Recipient to the Government at the following address:
 * 
 *         SMDC
 *         Attention SEDRIS (TO193) TPOC
 *         P.O. Box 1500
 *         Huntsville, AL  35807-3801
 * 
 *         or via electronic mail to:  se-mgmt@sedris.org
 * 
 *    5. No Warranty. This software is being delivered to you AS IS
 *       and there is no warranty, EXPRESS or IMPLIED, as to its use
 *       or performance.
 * 
 *       The RECIPIENT ASSUMES ALL RISKS, KNOWN AND UNKNOWN, OF USING
 *       THIS SOFTWARE.  The DEVELOPER EXPRESSLY DISCLAIMS, and the
 *       RECIPIENT WAIVES, ANY and ALL PERFORMANCE OR RESULTS YOU MAY
 *       OBTAIN BY USING THIS SOFTWARE OR DOCUMENTATION.  THERE IS
 *       NO WARRANTY, EXPRESS OR, IMPLIED, AS TO NON-INFRINGEMENT OF
 *       THIRD PARTY RIGHTS, MERCHANTABILITY, OR FITNESS FOR ANY
 *       PARTICULAR PURPOSE.  IN NO EVENT WILL THE DEVELOPER, THE
 *       UNITED STATES GOVERNMENT OR ANYONE ELSE ASSOCIATED WITH THE
 *       DEVELOPMENT OF THIS SOFTWARE BE HELD LIABLE FOR ANY CONSEQUENTIAL,
 *       INCIDENTAL OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS
 *       OR LOST SAVINGS WHATSOEVER.
 */

/** @file seDRMStampBehaviour.h
@author Warren Macchi (Accent Geographic)
@brief Accessors to the seDRMStampBehaviour (262) class.
*/

#ifndef _seDRMStampBehaviour_h
#define _seDRMStampBehaviour_h

#include "seDRMBase.h"

namespace sedris {

/** seDRMStampBehaviour wraps the DRM <a href="../drm/classes/StampBehaviour.htm">&lt;Stamp_Behaviour&gt;</a> class.
@author Warren Macchi
@version Revision: 1.8
@see seDRMBase
*/
class seDRMStampBehaviour : public seDRMBase
{
public:

    /// Default constructor
    seDRMStampBehaviour() {}

    /// Constructor for seDRM... class conversions
    seDRMStampBehaviour( const seObject &other ) : seDRMBase(other) {}

    /// Get field <a href="../drm/classes/StampBehaviour.htm#u_axis_limits">u_axis_limits</a>
    const SE_Rotation_Data& get_u_axis_limits()
    {
        DRMBASE_RET_FIELDS(Stamp_Behaviour, u_axis_limits);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#u_axis_limits">u_axis_limits</a>
    void set_u_axis_limits( const SE_Rotation_Data& u_axis_limits )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, u_axis_limits, u_axis_limits);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#u_axis_limits">u_axis_limits</a> by parameter list
    void set_u_axis_limits
    (
         SE_Long_Float counterclockwise_limit,
         SE_Long_Float clockwise_limit
    )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, u_axis_limits.counterclockwise_limit, counterclockwise_limit);
        DRMBASE_SET_FIELDS(Stamp_Behaviour, u_axis_limits.clockwise_limit, clockwise_limit);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#u_axis_limits_counterclockwise_limit">u_axis_limits_counterclockwise_limit</a>
    void set_u_axis_limits_counterclockwise_limit( SE_Long_Float counterclockwise_limit )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, u_axis_limits.counterclockwise_limit, counterclockwise_limit);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#u_axis_limits_clockwise_limit">u_axis_limits_clockwise_limit</a>
    void set_u_axis_limits_clockwise_limit( SE_Long_Float clockwise_limit )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, u_axis_limits.clockwise_limit, clockwise_limit);
    }

    /// Get field <a href="../drm/classes/StampBehaviour.htm#v_axis_limits">v_axis_limits</a>
    const SE_Rotation_Data& get_v_axis_limits()
    {
        DRMBASE_RET_FIELDS(Stamp_Behaviour, v_axis_limits);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#v_axis_limits">v_axis_limits</a>
    void set_v_axis_limits( const SE_Rotation_Data& v_axis_limits )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, v_axis_limits, v_axis_limits);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#v_axis_limits">v_axis_limits</a> by parameter list
    void set_v_axis_limits
    (
         SE_Long_Float counterclockwise_limit,
         SE_Long_Float clockwise_limit
    )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, v_axis_limits.counterclockwise_limit, counterclockwise_limit);
        DRMBASE_SET_FIELDS(Stamp_Behaviour, v_axis_limits.clockwise_limit, clockwise_limit);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#v_axis_limits_counterclockwise_limit">v_axis_limits_counterclockwise_limit</a>
    void set_v_axis_limits_counterclockwise_limit( SE_Long_Float counterclockwise_limit )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, v_axis_limits.counterclockwise_limit, counterclockwise_limit);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#v_axis_limits_clockwise_limit">v_axis_limits_clockwise_limit</a>
    void set_v_axis_limits_clockwise_limit( SE_Long_Float clockwise_limit )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, v_axis_limits.clockwise_limit, clockwise_limit);
    }

    /// Get field <a href="../drm/classes/StampBehaviour.htm#w_axis_limits">w_axis_limits</a>
    const SE_Rotation_Data& get_w_axis_limits()
    {
        DRMBASE_RET_FIELDS(Stamp_Behaviour, w_axis_limits);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#w_axis_limits">w_axis_limits</a>
    void set_w_axis_limits( const SE_Rotation_Data& w_axis_limits )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, w_axis_limits, w_axis_limits);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#w_axis_limits">w_axis_limits</a> by parameter list
    void set_w_axis_limits
    (
         SE_Long_Float counterclockwise_limit,
         SE_Long_Float clockwise_limit
    )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, w_axis_limits.counterclockwise_limit, counterclockwise_limit);
        DRMBASE_SET_FIELDS(Stamp_Behaviour, w_axis_limits.clockwise_limit, clockwise_limit);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#w_axis_limits_counterclockwise_limit">w_axis_limits_counterclockwise_limit</a>
    void set_w_axis_limits_counterclockwise_limit( SE_Long_Float counterclockwise_limit )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, w_axis_limits.counterclockwise_limit, counterclockwise_limit);
    }

    /// Set field <a href="../drm/classes/StampBehaviour.htm#w_axis_limits_clockwise_limit">w_axis_limits_clockwise_limit</a>
    void set_w_axis_limits_clockwise_limit( SE_Long_Float clockwise_limit )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Stamp_Behaviour, w_axis_limits.clockwise_limit, clockwise_limit);
    }

    /** Gets the DRM class type this object can reference (mostly internal use).
        @warning Don't confuse with getDRMClass(), which is dependent on the
            actual type held by this DRM class object reference.
        @return SE_CLS_DRM_STAMP_BEHAVIOUR
    */
    virtual SE_DRM_Class getClassType() const
    {
        return SE_CLS_DRM_STAMP_BEHAVIOUR;
    }

};

} // namespace sedris

#endif // _seDRMStampBehaviour_h
