/*
 *  Copyright (c) 2006 Accent Geographic. All rights reserved.
 *  See the license file for licensing information.
 *  Created: Wed Jul 26 23:47:08 2006
 *
 *  DO NOT EDIT THIS FILE! (Autogenerated)
 */

// SEDRIS C++ SDK Release 4.1.4 - July 1, 2011

/*
 *                             NOTICE
 * 
 * This software is provided openly and freely for use in representing and
 * interchanging environmental data & databases.
 * 
 * This software was developed for use by the United States Government with
 * unlimited rights.  The software was developed under contract
 * DASG60-02-D-0006 TO-193 by Science Applications International Corporation.
 * The software is unclassified and is deemed as Distribution A, approved
 * for Public Release.
 * 
 * Use by others is permitted only upon the ACCEPTANCE OF THE TERMS AND
 * CONDITIONS, AS STIPULATED UNDER THE FOLLOWING PROVISIONS:
 * 
 *    1. Recipient may make unlimited copies of this software and give
 *       copies to other persons or entities as long as the copies contain
 *       this NOTICE, and as long as the same copyright notices that
 *       appear on, or in, this software remain.
 * 
 *    2. Trademarks. All trademarks belong to their respective trademark
 *       holders.  Third-Party applications/software/information are
 *       copyrighted by their respective owners.
 * 
 *    3. Recipient agrees to forfeit all intellectual property and
 *       ownership rights for any version created from the modification
 *       or adaptation of this software, including versions created from
 *       the translation and/or reverse engineering of the software design.
 * 
 *    4. Transfer.  Recipient may not sell, rent, lease, or sublicense
 *       this software.  Recipient may, however enable another person
 *       or entity the rights to use this software, provided that this
 *       AGREEMENT and NOTICE is furnished along with the software and
 *       /or software system utilizing this software.
 * 
 *       All revisions, modifications, created by the Recipient, to this
 *       software and/or related technical data shall be forwarded by the
 *       Recipient to the Government at the following address:
 * 
 *         SMDC
 *         Attention SEDRIS (TO193) TPOC
 *         P.O. Box 1500
 *         Huntsville, AL  35807-3801
 * 
 *         or via electronic mail to:  se-mgmt@sedris.org
 * 
 *    5. No Warranty. This software is being delivered to you AS IS
 *       and there is no warranty, EXPRESS or IMPLIED, as to its use
 *       or performance.
 * 
 *       The RECIPIENT ASSUMES ALL RISKS, KNOWN AND UNKNOWN, OF USING
 *       THIS SOFTWARE.  The DEVELOPER EXPRESSLY DISCLAIMS, and the
 *       RECIPIENT WAIVES, ANY and ALL PERFORMANCE OR RESULTS YOU MAY
 *       OBTAIN BY USING THIS SOFTWARE OR DOCUMENTATION.  THERE IS
 *       NO WARRANTY, EXPRESS OR, IMPLIED, AS TO NON-INFRINGEMENT OF
 *       THIRD PARTY RIGHTS, MERCHANTABILITY, OR FITNESS FOR ANY
 *       PARTICULAR PURPOSE.  IN NO EVENT WILL THE DEVELOPER, THE
 *       UNITED STATES GOVERNMENT OR ANYONE ELSE ASSOCIATED WITH THE
 *       DEVELOPMENT OF THIS SOFTWARE BE HELD LIABLE FOR ANY CONSEQUENTIAL,
 *       INCIDENTAL OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS
 *       OR LOST SAVINGS WHATSOEVER.
 */

/** @file seDRMDataQuality.h
@author Warren Macchi (Accent Geographic)
@brief Accessors to the seDRMDataQuality (50) class.
*/

#ifndef _seDRMDataQuality_h
#define _seDRMDataQuality_h

#include "seDRMBase.h"

namespace sedris {

/** seDRMDataQuality wraps the DRM <a href="../drm/classes/DataQuality.htm">&lt;Data_Quality&gt;</a> class.
@author Warren Macchi
@version Revision: 1.8
@see seDRMBase
*/
class seDRMDataQuality : public seDRMBase
{
public:

    /// Default constructor
    seDRMDataQuality() {}

    /// Constructor for seDRM... class conversions
    seDRMDataQuality( const seObject &other ) : seDRMBase(other) {}

    /// Get field <a href="../drm/classes/DataQuality.htm#fictional">fictional</a>
    SE_Boolean get_fictional()
    {
        DRMBASE_RET_FIELDS(Data_Quality, fictional);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#fictional">fictional</a>
    void set_fictional( SE_Boolean fictional )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Data_Quality, fictional, fictional);
    }

    /// Get field <a href="../drm/classes/DataQuality.htm#field_accuracy">field_accuracy</a>
    const SE_Data_Quality_Element& get_field_accuracy()
    {
        DRMBASE_RET_FIELDS(Data_Quality, field_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy">field_accuracy</a>
    void set_field_accuracy( const SE_Data_Quality_Element& field_accuracy )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Data_Quality_Element(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy), field_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy">field_accuracy</a> by parameter list
    void set_field_accuracy
    (
         const SE_String& name_of_measure,
         const SE_String& measure_identification,
         const SE_String& measure_description,
         const SE_String& evaluation_method_type,
         const SE_String& evaluation_method_description,
         const SE_String& evaluation_procedure,
         const SE_String& data_time,
         const SE_String& result
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.name_of_measure), name_of_measure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.measure_identification), measure_identification);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.measure_description), measure_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_method_type), evaluation_method_type);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_method_description), evaluation_method_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_procedure), evaluation_procedure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.data_time), data_time);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.result), result);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_name_of_measure">field_accuracy.name_of_measure</a> by parameter list
    void set_field_accuracy_name_of_measure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.name_of_measure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_name_of_measure">field_accuracy_name_of_measure</a>
    void set_field_accuracy_name_of_measure( const SE_String& name_of_measure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.name_of_measure), name_of_measure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_measure_identification">field_accuracy.measure_identification</a> by parameter list
    void set_field_accuracy_measure_identification
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.measure_identification), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_measure_identification">field_accuracy_measure_identification</a>
    void set_field_accuracy_measure_identification( const SE_String& measure_identification )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.measure_identification), measure_identification);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_measure_description">field_accuracy.measure_description</a> by parameter list
    void set_field_accuracy_measure_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.measure_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_measure_description">field_accuracy_measure_description</a>
    void set_field_accuracy_measure_description( const SE_String& measure_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.measure_description), measure_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_evaluation_method_type">field_accuracy.evaluation_method_type</a> by parameter list
    void set_field_accuracy_evaluation_method_type
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_method_type), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_evaluation_method_type">field_accuracy_evaluation_method_type</a>
    void set_field_accuracy_evaluation_method_type( const SE_String& evaluation_method_type )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_method_type), evaluation_method_type);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_evaluation_method_description">field_accuracy.evaluation_method_description</a> by parameter list
    void set_field_accuracy_evaluation_method_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_method_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_evaluation_method_description">field_accuracy_evaluation_method_description</a>
    void set_field_accuracy_evaluation_method_description( const SE_String& evaluation_method_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_method_description), evaluation_method_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_evaluation_procedure">field_accuracy.evaluation_procedure</a> by parameter list
    void set_field_accuracy_evaluation_procedure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_procedure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_evaluation_procedure">field_accuracy_evaluation_procedure</a>
    void set_field_accuracy_evaluation_procedure( const SE_String& evaluation_procedure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.evaluation_procedure), evaluation_procedure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_data_time">field_accuracy.data_time</a> by parameter list
    void set_field_accuracy_data_time
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.data_time), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_data_time">field_accuracy_data_time</a>
    void set_field_accuracy_data_time( const SE_String& data_time )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.data_time), data_time);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_result">field_accuracy.result</a> by parameter list
    void set_field_accuracy_result
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.result), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#field_accuracy_result">field_accuracy_result</a>
    void set_field_accuracy_result( const SE_String& result )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, field_accuracy.result), result);
    }

    /// Get field <a href="../drm/classes/DataQuality.htm#logical_consistency">logical_consistency</a>
    const SE_Data_Quality_Element& get_logical_consistency()
    {
        DRMBASE_RET_FIELDS(Data_Quality, logical_consistency);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency">logical_consistency</a>
    void set_logical_consistency( const SE_Data_Quality_Element& logical_consistency )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Data_Quality_Element(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency), logical_consistency);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency">logical_consistency</a> by parameter list
    void set_logical_consistency
    (
         const SE_String& name_of_measure,
         const SE_String& measure_identification,
         const SE_String& measure_description,
         const SE_String& evaluation_method_type,
         const SE_String& evaluation_method_description,
         const SE_String& evaluation_procedure,
         const SE_String& data_time,
         const SE_String& result
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.name_of_measure), name_of_measure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.measure_identification), measure_identification);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.measure_description), measure_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_method_type), evaluation_method_type);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_method_description), evaluation_method_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_procedure), evaluation_procedure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.data_time), data_time);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.result), result);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_name_of_measure">logical_consistency.name_of_measure</a> by parameter list
    void set_logical_consistency_name_of_measure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.name_of_measure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_name_of_measure">logical_consistency_name_of_measure</a>
    void set_logical_consistency_name_of_measure( const SE_String& name_of_measure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.name_of_measure), name_of_measure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_measure_identification">logical_consistency.measure_identification</a> by parameter list
    void set_logical_consistency_measure_identification
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.measure_identification), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_measure_identification">logical_consistency_measure_identification</a>
    void set_logical_consistency_measure_identification( const SE_String& measure_identification )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.measure_identification), measure_identification);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_measure_description">logical_consistency.measure_description</a> by parameter list
    void set_logical_consistency_measure_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.measure_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_measure_description">logical_consistency_measure_description</a>
    void set_logical_consistency_measure_description( const SE_String& measure_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.measure_description), measure_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_evaluation_method_type">logical_consistency.evaluation_method_type</a> by parameter list
    void set_logical_consistency_evaluation_method_type
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_method_type), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_evaluation_method_type">logical_consistency_evaluation_method_type</a>
    void set_logical_consistency_evaluation_method_type( const SE_String& evaluation_method_type )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_method_type), evaluation_method_type);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_evaluation_method_description">logical_consistency.evaluation_method_description</a> by parameter list
    void set_logical_consistency_evaluation_method_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_method_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_evaluation_method_description">logical_consistency_evaluation_method_description</a>
    void set_logical_consistency_evaluation_method_description( const SE_String& evaluation_method_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_method_description), evaluation_method_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_evaluation_procedure">logical_consistency.evaluation_procedure</a> by parameter list
    void set_logical_consistency_evaluation_procedure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_procedure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_evaluation_procedure">logical_consistency_evaluation_procedure</a>
    void set_logical_consistency_evaluation_procedure( const SE_String& evaluation_procedure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.evaluation_procedure), evaluation_procedure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_data_time">logical_consistency.data_time</a> by parameter list
    void set_logical_consistency_data_time
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.data_time), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_data_time">logical_consistency_data_time</a>
    void set_logical_consistency_data_time( const SE_String& data_time )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.data_time), data_time);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_result">logical_consistency.result</a> by parameter list
    void set_logical_consistency_result
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.result), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#logical_consistency_result">logical_consistency_result</a>
    void set_logical_consistency_result( const SE_String& result )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, logical_consistency.result), result);
    }

    /// Get field <a href="../drm/classes/DataQuality.htm#completeness">completeness</a>
    const SE_Data_Quality_Element& get_completeness()
    {
        DRMBASE_RET_FIELDS(Data_Quality, completeness);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness">completeness</a>
    void set_completeness( const SE_Data_Quality_Element& completeness )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Data_Quality_Element(DRMBASE_ACC_FIELDS(Data_Quality, completeness), completeness);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness">completeness</a> by parameter list
    void set_completeness
    (
         const SE_String& name_of_measure,
         const SE_String& measure_identification,
         const SE_String& measure_description,
         const SE_String& evaluation_method_type,
         const SE_String& evaluation_method_description,
         const SE_String& evaluation_procedure,
         const SE_String& data_time,
         const SE_String& result
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.name_of_measure), name_of_measure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.measure_identification), measure_identification);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.measure_description), measure_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_method_type), evaluation_method_type);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_method_description), evaluation_method_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_procedure), evaluation_procedure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.data_time), data_time);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.result), result);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_name_of_measure">completeness.name_of_measure</a> by parameter list
    void set_completeness_name_of_measure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.name_of_measure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_name_of_measure">completeness_name_of_measure</a>
    void set_completeness_name_of_measure( const SE_String& name_of_measure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.name_of_measure), name_of_measure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_measure_identification">completeness.measure_identification</a> by parameter list
    void set_completeness_measure_identification
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.measure_identification), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_measure_identification">completeness_measure_identification</a>
    void set_completeness_measure_identification( const SE_String& measure_identification )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.measure_identification), measure_identification);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_measure_description">completeness.measure_description</a> by parameter list
    void set_completeness_measure_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.measure_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_measure_description">completeness_measure_description</a>
    void set_completeness_measure_description( const SE_String& measure_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.measure_description), measure_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_evaluation_method_type">completeness.evaluation_method_type</a> by parameter list
    void set_completeness_evaluation_method_type
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_method_type), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_evaluation_method_type">completeness_evaluation_method_type</a>
    void set_completeness_evaluation_method_type( const SE_String& evaluation_method_type )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_method_type), evaluation_method_type);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_evaluation_method_description">completeness.evaluation_method_description</a> by parameter list
    void set_completeness_evaluation_method_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_method_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_evaluation_method_description">completeness_evaluation_method_description</a>
    void set_completeness_evaluation_method_description( const SE_String& evaluation_method_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_method_description), evaluation_method_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_evaluation_procedure">completeness.evaluation_procedure</a> by parameter list
    void set_completeness_evaluation_procedure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_procedure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_evaluation_procedure">completeness_evaluation_procedure</a>
    void set_completeness_evaluation_procedure( const SE_String& evaluation_procedure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.evaluation_procedure), evaluation_procedure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_data_time">completeness.data_time</a> by parameter list
    void set_completeness_data_time
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.data_time), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_data_time">completeness_data_time</a>
    void set_completeness_data_time( const SE_String& data_time )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.data_time), data_time);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_result">completeness.result</a> by parameter list
    void set_completeness_result
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.result), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#completeness_result">completeness_result</a>
    void set_completeness_result( const SE_String& result )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, completeness.result), result);
    }

    /// Get field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy">abs_horiz_pos_accuracy</a>
    const SE_Data_Quality_Element& get_abs_horiz_pos_accuracy()
    {
        DRMBASE_RET_FIELDS(Data_Quality, abs_horiz_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy">abs_horiz_pos_accuracy</a>
    void set_abs_horiz_pos_accuracy( const SE_Data_Quality_Element& abs_horiz_pos_accuracy )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Data_Quality_Element(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy), abs_horiz_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy">abs_horiz_pos_accuracy</a> by parameter list
    void set_abs_horiz_pos_accuracy
    (
         const SE_String& name_of_measure,
         const SE_String& measure_identification,
         const SE_String& measure_description,
         const SE_String& evaluation_method_type,
         const SE_String& evaluation_method_description,
         const SE_String& evaluation_procedure,
         const SE_String& data_time,
         const SE_String& result
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.name_of_measure), name_of_measure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.measure_identification), measure_identification);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.measure_description), measure_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_method_type), evaluation_method_type);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_method_description), evaluation_method_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_procedure), evaluation_procedure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.data_time), data_time);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.result), result);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_name_of_measure">abs_horiz_pos_accuracy.name_of_measure</a> by parameter list
    void set_abs_horiz_pos_accuracy_name_of_measure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.name_of_measure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_name_of_measure">abs_horiz_pos_accuracy_name_of_measure</a>
    void set_abs_horiz_pos_accuracy_name_of_measure( const SE_String& name_of_measure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.name_of_measure), name_of_measure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_measure_identification">abs_horiz_pos_accuracy.measure_identification</a> by parameter list
    void set_abs_horiz_pos_accuracy_measure_identification
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.measure_identification), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_measure_identification">abs_horiz_pos_accuracy_measure_identification</a>
    void set_abs_horiz_pos_accuracy_measure_identification( const SE_String& measure_identification )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.measure_identification), measure_identification);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_measure_description">abs_horiz_pos_accuracy.measure_description</a> by parameter list
    void set_abs_horiz_pos_accuracy_measure_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.measure_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_measure_description">abs_horiz_pos_accuracy_measure_description</a>
    void set_abs_horiz_pos_accuracy_measure_description( const SE_String& measure_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.measure_description), measure_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_evaluation_method_type">abs_horiz_pos_accuracy.evaluation_method_type</a> by parameter list
    void set_abs_horiz_pos_accuracy_evaluation_method_type
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_method_type), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_evaluation_method_type">abs_horiz_pos_accuracy_evaluation_method_type</a>
    void set_abs_horiz_pos_accuracy_evaluation_method_type( const SE_String& evaluation_method_type )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_method_type), evaluation_method_type);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_evaluation_method_description">abs_horiz_pos_accuracy.evaluation_method_description</a> by parameter list
    void set_abs_horiz_pos_accuracy_evaluation_method_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_method_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_evaluation_method_description">abs_horiz_pos_accuracy_evaluation_method_description</a>
    void set_abs_horiz_pos_accuracy_evaluation_method_description( const SE_String& evaluation_method_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_method_description), evaluation_method_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_evaluation_procedure">abs_horiz_pos_accuracy.evaluation_procedure</a> by parameter list
    void set_abs_horiz_pos_accuracy_evaluation_procedure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_procedure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_evaluation_procedure">abs_horiz_pos_accuracy_evaluation_procedure</a>
    void set_abs_horiz_pos_accuracy_evaluation_procedure( const SE_String& evaluation_procedure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.evaluation_procedure), evaluation_procedure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_data_time">abs_horiz_pos_accuracy.data_time</a> by parameter list
    void set_abs_horiz_pos_accuracy_data_time
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.data_time), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_data_time">abs_horiz_pos_accuracy_data_time</a>
    void set_abs_horiz_pos_accuracy_data_time( const SE_String& data_time )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.data_time), data_time);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_result">abs_horiz_pos_accuracy.result</a> by parameter list
    void set_abs_horiz_pos_accuracy_result
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.result), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_horiz_pos_accuracy_result">abs_horiz_pos_accuracy_result</a>
    void set_abs_horiz_pos_accuracy_result( const SE_String& result )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_horiz_pos_accuracy.result), result);
    }

    /// Get field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy">rel_horiz_pos_accuracy</a>
    const SE_Data_Quality_Element& get_rel_horiz_pos_accuracy()
    {
        DRMBASE_RET_FIELDS(Data_Quality, rel_horiz_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy">rel_horiz_pos_accuracy</a>
    void set_rel_horiz_pos_accuracy( const SE_Data_Quality_Element& rel_horiz_pos_accuracy )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Data_Quality_Element(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy), rel_horiz_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy">rel_horiz_pos_accuracy</a> by parameter list
    void set_rel_horiz_pos_accuracy
    (
         const SE_String& name_of_measure,
         const SE_String& measure_identification,
         const SE_String& measure_description,
         const SE_String& evaluation_method_type,
         const SE_String& evaluation_method_description,
         const SE_String& evaluation_procedure,
         const SE_String& data_time,
         const SE_String& result
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.name_of_measure), name_of_measure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.measure_identification), measure_identification);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.measure_description), measure_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_method_type), evaluation_method_type);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_method_description), evaluation_method_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_procedure), evaluation_procedure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.data_time), data_time);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.result), result);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_name_of_measure">rel_horiz_pos_accuracy.name_of_measure</a> by parameter list
    void set_rel_horiz_pos_accuracy_name_of_measure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.name_of_measure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_name_of_measure">rel_horiz_pos_accuracy_name_of_measure</a>
    void set_rel_horiz_pos_accuracy_name_of_measure( const SE_String& name_of_measure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.name_of_measure), name_of_measure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_measure_identification">rel_horiz_pos_accuracy.measure_identification</a> by parameter list
    void set_rel_horiz_pos_accuracy_measure_identification
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.measure_identification), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_measure_identification">rel_horiz_pos_accuracy_measure_identification</a>
    void set_rel_horiz_pos_accuracy_measure_identification( const SE_String& measure_identification )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.measure_identification), measure_identification);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_measure_description">rel_horiz_pos_accuracy.measure_description</a> by parameter list
    void set_rel_horiz_pos_accuracy_measure_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.measure_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_measure_description">rel_horiz_pos_accuracy_measure_description</a>
    void set_rel_horiz_pos_accuracy_measure_description( const SE_String& measure_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.measure_description), measure_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_evaluation_method_type">rel_horiz_pos_accuracy.evaluation_method_type</a> by parameter list
    void set_rel_horiz_pos_accuracy_evaluation_method_type
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_method_type), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_evaluation_method_type">rel_horiz_pos_accuracy_evaluation_method_type</a>
    void set_rel_horiz_pos_accuracy_evaluation_method_type( const SE_String& evaluation_method_type )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_method_type), evaluation_method_type);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_evaluation_method_description">rel_horiz_pos_accuracy.evaluation_method_description</a> by parameter list
    void set_rel_horiz_pos_accuracy_evaluation_method_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_method_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_evaluation_method_description">rel_horiz_pos_accuracy_evaluation_method_description</a>
    void set_rel_horiz_pos_accuracy_evaluation_method_description( const SE_String& evaluation_method_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_method_description), evaluation_method_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_evaluation_procedure">rel_horiz_pos_accuracy.evaluation_procedure</a> by parameter list
    void set_rel_horiz_pos_accuracy_evaluation_procedure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_procedure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_evaluation_procedure">rel_horiz_pos_accuracy_evaluation_procedure</a>
    void set_rel_horiz_pos_accuracy_evaluation_procedure( const SE_String& evaluation_procedure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.evaluation_procedure), evaluation_procedure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_data_time">rel_horiz_pos_accuracy.data_time</a> by parameter list
    void set_rel_horiz_pos_accuracy_data_time
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.data_time), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_data_time">rel_horiz_pos_accuracy_data_time</a>
    void set_rel_horiz_pos_accuracy_data_time( const SE_String& data_time )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.data_time), data_time);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_result">rel_horiz_pos_accuracy.result</a> by parameter list
    void set_rel_horiz_pos_accuracy_result
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.result), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_horiz_pos_accuracy_result">rel_horiz_pos_accuracy_result</a>
    void set_rel_horiz_pos_accuracy_result( const SE_String& result )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_horiz_pos_accuracy.result), result);
    }

    /// Get field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy">abs_vert_pos_accuracy</a>
    const SE_Data_Quality_Element& get_abs_vert_pos_accuracy()
    {
        DRMBASE_RET_FIELDS(Data_Quality, abs_vert_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy">abs_vert_pos_accuracy</a>
    void set_abs_vert_pos_accuracy( const SE_Data_Quality_Element& abs_vert_pos_accuracy )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Data_Quality_Element(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy), abs_vert_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy">abs_vert_pos_accuracy</a> by parameter list
    void set_abs_vert_pos_accuracy
    (
         const SE_String& name_of_measure,
         const SE_String& measure_identification,
         const SE_String& measure_description,
         const SE_String& evaluation_method_type,
         const SE_String& evaluation_method_description,
         const SE_String& evaluation_procedure,
         const SE_String& data_time,
         const SE_String& result
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.name_of_measure), name_of_measure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.measure_identification), measure_identification);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.measure_description), measure_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_method_type), evaluation_method_type);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_method_description), evaluation_method_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_procedure), evaluation_procedure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.data_time), data_time);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.result), result);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_name_of_measure">abs_vert_pos_accuracy.name_of_measure</a> by parameter list
    void set_abs_vert_pos_accuracy_name_of_measure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.name_of_measure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_name_of_measure">abs_vert_pos_accuracy_name_of_measure</a>
    void set_abs_vert_pos_accuracy_name_of_measure( const SE_String& name_of_measure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.name_of_measure), name_of_measure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_measure_identification">abs_vert_pos_accuracy.measure_identification</a> by parameter list
    void set_abs_vert_pos_accuracy_measure_identification
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.measure_identification), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_measure_identification">abs_vert_pos_accuracy_measure_identification</a>
    void set_abs_vert_pos_accuracy_measure_identification( const SE_String& measure_identification )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.measure_identification), measure_identification);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_measure_description">abs_vert_pos_accuracy.measure_description</a> by parameter list
    void set_abs_vert_pos_accuracy_measure_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.measure_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_measure_description">abs_vert_pos_accuracy_measure_description</a>
    void set_abs_vert_pos_accuracy_measure_description( const SE_String& measure_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.measure_description), measure_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_evaluation_method_type">abs_vert_pos_accuracy.evaluation_method_type</a> by parameter list
    void set_abs_vert_pos_accuracy_evaluation_method_type
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_method_type), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_evaluation_method_type">abs_vert_pos_accuracy_evaluation_method_type</a>
    void set_abs_vert_pos_accuracy_evaluation_method_type( const SE_String& evaluation_method_type )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_method_type), evaluation_method_type);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_evaluation_method_description">abs_vert_pos_accuracy.evaluation_method_description</a> by parameter list
    void set_abs_vert_pos_accuracy_evaluation_method_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_method_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_evaluation_method_description">abs_vert_pos_accuracy_evaluation_method_description</a>
    void set_abs_vert_pos_accuracy_evaluation_method_description( const SE_String& evaluation_method_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_method_description), evaluation_method_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_evaluation_procedure">abs_vert_pos_accuracy.evaluation_procedure</a> by parameter list
    void set_abs_vert_pos_accuracy_evaluation_procedure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_procedure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_evaluation_procedure">abs_vert_pos_accuracy_evaluation_procedure</a>
    void set_abs_vert_pos_accuracy_evaluation_procedure( const SE_String& evaluation_procedure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.evaluation_procedure), evaluation_procedure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_data_time">abs_vert_pos_accuracy.data_time</a> by parameter list
    void set_abs_vert_pos_accuracy_data_time
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.data_time), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_data_time">abs_vert_pos_accuracy_data_time</a>
    void set_abs_vert_pos_accuracy_data_time( const SE_String& data_time )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.data_time), data_time);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_result">abs_vert_pos_accuracy.result</a> by parameter list
    void set_abs_vert_pos_accuracy_result
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.result), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#abs_vert_pos_accuracy_result">abs_vert_pos_accuracy_result</a>
    void set_abs_vert_pos_accuracy_result( const SE_String& result )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, abs_vert_pos_accuracy.result), result);
    }

    /// Get field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy">rel_vert_pos_accuracy</a>
    const SE_Data_Quality_Element& get_rel_vert_pos_accuracy()
    {
        DRMBASE_RET_FIELDS(Data_Quality, rel_vert_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy">rel_vert_pos_accuracy</a>
    void set_rel_vert_pos_accuracy( const SE_Data_Quality_Element& rel_vert_pos_accuracy )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Data_Quality_Element(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy), rel_vert_pos_accuracy);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy">rel_vert_pos_accuracy</a> by parameter list
    void set_rel_vert_pos_accuracy
    (
         const SE_String& name_of_measure,
         const SE_String& measure_identification,
         const SE_String& measure_description,
         const SE_String& evaluation_method_type,
         const SE_String& evaluation_method_description,
         const SE_String& evaluation_procedure,
         const SE_String& data_time,
         const SE_String& result
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.name_of_measure), name_of_measure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.measure_identification), measure_identification);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.measure_description), measure_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_method_type), evaluation_method_type);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_method_description), evaluation_method_description);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_procedure), evaluation_procedure);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.data_time), data_time);
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.result), result);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_name_of_measure">rel_vert_pos_accuracy.name_of_measure</a> by parameter list
    void set_rel_vert_pos_accuracy_name_of_measure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.name_of_measure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_name_of_measure">rel_vert_pos_accuracy_name_of_measure</a>
    void set_rel_vert_pos_accuracy_name_of_measure( const SE_String& name_of_measure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.name_of_measure), name_of_measure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_measure_identification">rel_vert_pos_accuracy.measure_identification</a> by parameter list
    void set_rel_vert_pos_accuracy_measure_identification
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.measure_identification), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_measure_identification">rel_vert_pos_accuracy_measure_identification</a>
    void set_rel_vert_pos_accuracy_measure_identification( const SE_String& measure_identification )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.measure_identification), measure_identification);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_measure_description">rel_vert_pos_accuracy.measure_description</a> by parameter list
    void set_rel_vert_pos_accuracy_measure_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.measure_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_measure_description">rel_vert_pos_accuracy_measure_description</a>
    void set_rel_vert_pos_accuracy_measure_description( const SE_String& measure_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.measure_description), measure_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_evaluation_method_type">rel_vert_pos_accuracy.evaluation_method_type</a> by parameter list
    void set_rel_vert_pos_accuracy_evaluation_method_type
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_method_type), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_evaluation_method_type">rel_vert_pos_accuracy_evaluation_method_type</a>
    void set_rel_vert_pos_accuracy_evaluation_method_type( const SE_String& evaluation_method_type )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_method_type), evaluation_method_type);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_evaluation_method_description">rel_vert_pos_accuracy.evaluation_method_description</a> by parameter list
    void set_rel_vert_pos_accuracy_evaluation_method_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_method_description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_evaluation_method_description">rel_vert_pos_accuracy_evaluation_method_description</a>
    void set_rel_vert_pos_accuracy_evaluation_method_description( const SE_String& evaluation_method_description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_method_description), evaluation_method_description);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_evaluation_procedure">rel_vert_pos_accuracy.evaluation_procedure</a> by parameter list
    void set_rel_vert_pos_accuracy_evaluation_procedure
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_procedure), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_evaluation_procedure">rel_vert_pos_accuracy_evaluation_procedure</a>
    void set_rel_vert_pos_accuracy_evaluation_procedure( const SE_String& evaluation_procedure )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.evaluation_procedure), evaluation_procedure);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_data_time">rel_vert_pos_accuracy.data_time</a> by parameter list
    void set_rel_vert_pos_accuracy_data_time
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.data_time), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_data_time">rel_vert_pos_accuracy_data_time</a>
    void set_rel_vert_pos_accuracy_data_time( const SE_String& data_time )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.data_time), data_time);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_result">rel_vert_pos_accuracy.result</a> by parameter list
    void set_rel_vert_pos_accuracy_result
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.result), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/DataQuality.htm#rel_vert_pos_accuracy_result">rel_vert_pos_accuracy_result</a>
    void set_rel_vert_pos_accuracy_result( const SE_String& result )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Data_Quality, rel_vert_pos_accuracy.result), result);
    }

    /** Gets the DRM class type this object can reference (mostly internal use).
        @warning Don't confuse with getDRMClass(), which is dependent on the
            actual type held by this DRM class object reference.
        @return SE_CLS_DRM_DATA_QUALITY
    */
    virtual SE_DRM_Class getClassType() const
    {
        return SE_CLS_DRM_DATA_QUALITY;
    }

};

} // namespace sedris

#endif // _seDRMDataQuality_h
