/*
 *  Copyright (c) 2006 Accent Geographic. All rights reserved.
 *  See the license file for licensing information.
 *  Created: Wed Jul 26 23:47:08 2006
 *
 *  DO NOT EDIT THIS FILE! (Autogenerated)
 */

// SEDRIS C++ SDK Release 4.1.4 - July 1, 2011

/*
 *                             NOTICE
 * 
 * This software is provided openly and freely for use in representing and
 * interchanging environmental data & databases.
 * 
 * This software was developed for use by the United States Government with
 * unlimited rights.  The software was developed under contract
 * DASG60-02-D-0006 TO-193 by Science Applications International Corporation.
 * The software is unclassified and is deemed as Distribution A, approved
 * for Public Release.
 * 
 * Use by others is permitted only upon the ACCEPTANCE OF THE TERMS AND
 * CONDITIONS, AS STIPULATED UNDER THE FOLLOWING PROVISIONS:
 * 
 *    1. Recipient may make unlimited copies of this software and give
 *       copies to other persons or entities as long as the copies contain
 *       this NOTICE, and as long as the same copyright notices that
 *       appear on, or in, this software remain.
 * 
 *    2. Trademarks. All trademarks belong to their respective trademark
 *       holders.  Third-Party applications/software/information are
 *       copyrighted by their respective owners.
 * 
 *    3. Recipient agrees to forfeit all intellectual property and
 *       ownership rights for any version created from the modification
 *       or adaptation of this software, including versions created from
 *       the translation and/or reverse engineering of the software design.
 * 
 *    4. Transfer.  Recipient may not sell, rent, lease, or sublicense
 *       this software.  Recipient may, however enable another person
 *       or entity the rights to use this software, provided that this
 *       AGREEMENT and NOTICE is furnished along with the software and
 *       /or software system utilizing this software.
 * 
 *       All revisions, modifications, created by the Recipient, to this
 *       software and/or related technical data shall be forwarded by the
 *       Recipient to the Government at the following address:
 * 
 *         SMDC
 *         Attention SEDRIS (TO193) TPOC
 *         P.O. Box 1500
 *         Huntsville, AL  35807-3801
 * 
 *         or via electronic mail to:  se-mgmt@sedris.org
 * 
 *    5. No Warranty. This software is being delivered to you AS IS
 *       and there is no warranty, EXPRESS or IMPLIED, as to its use
 *       or performance.
 * 
 *       The RECIPIENT ASSUMES ALL RISKS, KNOWN AND UNKNOWN, OF USING
 *       THIS SOFTWARE.  The DEVELOPER EXPRESSLY DISCLAIMS, and the
 *       RECIPIENT WAIVES, ANY and ALL PERFORMANCE OR RESULTS YOU MAY
 *       OBTAIN BY USING THIS SOFTWARE OR DOCUMENTATION.  THERE IS
 *       NO WARRANTY, EXPRESS OR, IMPLIED, AS TO NON-INFRINGEMENT OF
 *       THIRD PARTY RIGHTS, MERCHANTABILITY, OR FITNESS FOR ANY
 *       PARTICULAR PURPOSE.  IN NO EVENT WILL THE DEVELOPER, THE
 *       UNITED STATES GOVERNMENT OR ANYONE ELSE ASSOCIATED WITH THE
 *       DEVELOPMENT OF THIS SOFTWARE BE HELD LIABLE FOR ANY CONSEQUENTIAL,
 *       INCIDENTAL OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS
 *       OR LOST SAVINGS WHATSOEVER.
 */

/** @file seDRMResponsibleParty.h
@author Warren Macchi (Accent Geographic)
@brief Accessors to the seDRMResponsibleParty (224) class.
*/

#ifndef _seDRMResponsibleParty_h
#define _seDRMResponsibleParty_h

#include "seDRMBase.h"

namespace sedris {

/** seDRMResponsibleParty wraps the DRM <a href="../drm/classes/ResponsibleParty.htm">&lt;Responsible_Party&gt;</a> class.
@author Warren Macchi
@version Revision: 1.8
@see seDRMBase
*/
class seDRMResponsibleParty : public seDRMBase
{
public:

    /// Default constructor
    seDRMResponsibleParty() {}

    /// Constructor for seDRM... class conversions
    seDRMResponsibleParty( const seObject &other ) : seDRMBase(other) {}

    /// Get field <a href="../drm/classes/ResponsibleParty.htm#individual_name">individual_name</a>
    const SE_String& get_individual_name()
    {
        DRMBASE_RET_FIELDS(Responsible_Party, individual_name);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#individual_name">individual_name</a> by parameter list
    void set_individual_name
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, individual_name), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#individual_name">individual_name</a>
    void set_individual_name( const SE_String& individual_name )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, individual_name), individual_name);
    }

    /// Get field <a href="../drm/classes/ResponsibleParty.htm#organization_name">organization_name</a>
    const SE_String& get_organization_name()
    {
        DRMBASE_RET_FIELDS(Responsible_Party, organization_name);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#organization_name">organization_name</a> by parameter list
    void set_organization_name
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, organization_name), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#organization_name">organization_name</a>
    void set_organization_name( const SE_String& organization_name )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, organization_name), organization_name);
    }

    /// Get field <a href="../drm/classes/ResponsibleParty.htm#position_name">position_name</a>
    const SE_String& get_position_name()
    {
        DRMBASE_RET_FIELDS(Responsible_Party, position_name);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#position_name">position_name</a> by parameter list
    void set_position_name
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, position_name), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#position_name">position_name</a>
    void set_position_name( const SE_String& position_name )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, position_name), position_name);
    }

    /// Get field <a href="../drm/classes/ResponsibleParty.htm#contact_information">contact_information</a>
    const SE_Contact_Information& get_contact_information()
    {
        DRMBASE_RET_FIELDS(Responsible_Party, contact_information);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information">contact_information</a>
    void set_contact_information( const SE_Contact_Information& contact_information )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Contact_Information(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information), contact_information);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information">contact_information</a> by parameter list
    void set_contact_information
    (
         const SE_Telephone_Information& phone,
         const SE_Address& address,
         const SE_CI_OnlineResource& online_resource,
         const SE_String& hours_of_service,
         const SE_String& contact_instructions
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Telephone_Information(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone), phone);
        set_SE_Address(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address), address);
        set_SE_CI_OnlineResource(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource), online_resource);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.hours_of_service), hours_of_service);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.contact_instructions), contact_instructions);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone">contact_information_phone</a>
    void set_contact_information_phone( const SE_Telephone_Information& phone )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Telephone_Information(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone), phone);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone">contact_information.phone</a> by parameter list
    void set_contact_information_phone
    (
         SE_Short_Integer_Unsigned voice_count,
         const SE_String* voice,
         SE_Short_Integer_Unsigned facsimile_count,
         const SE_String* facsimile,
         SE_Short_Integer_Unsigned tdd_tty_count,
         const SE_String* tdd_tty
    )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.phone.voice_count, voice_count);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.voice), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.voice_count), voice, voice_count);
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.phone.facsimile_count, facsimile_count);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.facsimile), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.facsimile_count), facsimile, facsimile_count);
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.phone.tdd_tty_count, tdd_tty_count);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.tdd_tty), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.tdd_tty_count), tdd_tty, tdd_tty_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone_voice_count">contact_information_phone_voice_count</a>
    void set_contact_information_phone_voice_count( SE_Short_Integer_Unsigned voice_count )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.phone.voice_count, voice_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone_voice">contact_information_phone_voice</a>
    void set_contact_information_phone_voice( const SE_String* voice, SE_Short_Integer_Unsigned voice_count )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.voice), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.voice_count), voice, voice_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone_facsimile_count">contact_information_phone_facsimile_count</a>
    void set_contact_information_phone_facsimile_count( SE_Short_Integer_Unsigned facsimile_count )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.phone.facsimile_count, facsimile_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone_facsimile">contact_information_phone_facsimile</a>
    void set_contact_information_phone_facsimile( const SE_String* facsimile, SE_Short_Integer_Unsigned facsimile_count )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.facsimile), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.facsimile_count), facsimile, facsimile_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone_tdd_tty_count">contact_information_phone_tdd_tty_count</a>
    void set_contact_information_phone_tdd_tty_count( SE_Short_Integer_Unsigned tdd_tty_count )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.phone.tdd_tty_count, tdd_tty_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_phone_tdd_tty">contact_information_phone_tdd_tty</a>
    void set_contact_information_phone_tdd_tty( const SE_String* tdd_tty, SE_Short_Integer_Unsigned tdd_tty_count )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.tdd_tty), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.phone.tdd_tty_count), tdd_tty, tdd_tty_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address">contact_information_address</a>
    void set_contact_information_address( const SE_Address& address )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_Address(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address), address);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address">contact_information.address</a> by parameter list
    void set_contact_information_address
    (
         SE_Short_Integer_Positive delivery_point_count,
         const SE_String* delivery_point,
         const SE_String& city,
         const SE_String& administrative_area,
         const SE_String& postal_code,
         const SE_Character country[3],
         SE_Short_Integer_Positive email_address_count,
         const SE_String* email_address
    )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.address.delivery_point_count, delivery_point_count);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.delivery_point), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.delivery_point_count), delivery_point, delivery_point_count);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.city), city);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.administrative_area), administrative_area);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.postal_code), postal_code);
        for ( int i=0; i < 3; i++ )
            DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.country)[i] = country[i];
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.address.email_address_count, email_address_count);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.email_address), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.email_address_count), email_address, email_address_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_delivery_point_count">contact_information_address_delivery_point_count</a>
    void set_contact_information_address_delivery_point_count( SE_Short_Integer_Positive delivery_point_count )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.address.delivery_point_count, delivery_point_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_delivery_point">contact_information_address_delivery_point</a>
    void set_contact_information_address_delivery_point( const SE_String* delivery_point, SE_Short_Integer_Positive delivery_point_count )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.delivery_point), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.delivery_point_count), delivery_point, delivery_point_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_city">contact_information.address.city</a> by parameter list
    void set_contact_information_address_city
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.city), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_city">contact_information_address_city</a>
    void set_contact_information_address_city( const SE_String& city )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.city), city);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_administrative_area">contact_information.address.administrative_area</a> by parameter list
    void set_contact_information_address_administrative_area
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.administrative_area), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_administrative_area">contact_information_address_administrative_area</a>
    void set_contact_information_address_administrative_area( const SE_String& administrative_area )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.administrative_area), administrative_area);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_postal_code">contact_information.address.postal_code</a> by parameter list
    void set_contact_information_address_postal_code
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.postal_code), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_postal_code">contact_information_address_postal_code</a>
    void set_contact_information_address_postal_code( const SE_String& postal_code )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.postal_code), postal_code);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_country">contact_information_address_country</a>
    void set_contact_information_address_country( const SE_Character country[3] )
    {
        DRMBASE_ALLOC_FIELDS;
        for ( int i=0; i < 3; i++ )
            DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.country)[i] = country[i];
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_email_address_count">contact_information_address_email_address_count</a>
    void set_contact_information_address_email_address_count( SE_Short_Integer_Positive email_address_count )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.address.email_address_count, email_address_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_address_email_address">contact_information_address_email_address</a>
    void set_contact_information_address_email_address( const SE_String* email_address, SE_Short_Integer_Positive email_address_count )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.email_address), DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.address.email_address_count), email_address, email_address_count);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource">contact_information_online_resource</a>
    void set_contact_information_online_resource( const SE_CI_OnlineResource& online_resource )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_CI_OnlineResource(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource), online_resource);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource">contact_information.online_resource</a> by parameter list
    void set_contact_information_online_resource
    (
         const SE_URL& linkage,
         const SE_String& protocol,
         const SE_String& application_profile,
         const SE_String& name,
         const SE_String& description,
         SE_CI_OnlineFunctionCode function
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_URL(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.linkage), linkage);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.protocol), protocol);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.application_profile), application_profile);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.name), name);
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.description), description);
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.online_resource.function, function);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_linkage">contact_information.online_resource.linkage</a> by parameter list
    void set_contact_information_online_resource_linkage
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_URL(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.linkage), characters, length);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_linkage">contact_information_online_resource_linkage</a>
    void set_contact_information_online_resource_linkage( const SE_URL& linkage )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_URL(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.linkage), linkage);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_protocol">contact_information.online_resource.protocol</a> by parameter list
    void set_contact_information_online_resource_protocol
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.protocol), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_protocol">contact_information_online_resource_protocol</a>
    void set_contact_information_online_resource_protocol( const SE_String& protocol )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.protocol), protocol);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_application_profile">contact_information.online_resource.application_profile</a> by parameter list
    void set_contact_information_online_resource_application_profile
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.application_profile), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_application_profile">contact_information_online_resource_application_profile</a>
    void set_contact_information_online_resource_application_profile( const SE_String& application_profile )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.application_profile), application_profile);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_name">contact_information.online_resource.name</a> by parameter list
    void set_contact_information_online_resource_name
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.name), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_name">contact_information_online_resource_name</a>
    void set_contact_information_online_resource_name( const SE_String& name )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.name), name);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_description">contact_information.online_resource.description</a> by parameter list
    void set_contact_information_online_resource_description
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.description), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_description">contact_information_online_resource_description</a>
    void set_contact_information_online_resource_description( const SE_String& description )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.online_resource.description), description);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_online_resource_function">contact_information_online_resource_function</a>
    void set_contact_information_online_resource_function( SE_CI_OnlineFunctionCode function )
    {
        DRMBASE_ALLOC_FIELDS;
        DRMBASE_SET_FIELDS(Responsible_Party, contact_information.online_resource.function, function);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_hours_of_service">contact_information.hours_of_service</a> by parameter list
    void set_contact_information_hours_of_service
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.hours_of_service), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_hours_of_service">contact_information_hours_of_service</a>
    void set_contact_information_hours_of_service( const SE_String& hours_of_service )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.hours_of_service), hours_of_service);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_contact_instructions">contact_information.contact_instructions</a> by parameter list
    void set_contact_information_contact_instructions
    (
        const SE_Character* characters,
        SE_Integer_Unsigned length=0,
        const SE_Locale& locale=SE_LOCALE_DEFAULT
    )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.contact_instructions), characters, length, locale);
    }

    /// Set field <a href="../drm/classes/ResponsibleParty.htm#contact_information_contact_instructions">contact_information_contact_instructions</a>
    void set_contact_information_contact_instructions( const SE_String& contact_instructions )
    {
        DRMBASE_ALLOC_FIELDS;
        set_SE_String(DRMBASE_ACC_FIELDS(Responsible_Party, contact_information.contact_instructions), contact_instructions);
    }

    /** Gets the DRM class type this object can reference (mostly internal use).
        @warning Don't confuse with getDRMClass(), which is dependent on the
            actual type held by this DRM class object reference.
        @return SE_CLS_DRM_RESPONSIBLE_PARTY
    */
    virtual SE_DRM_Class getClassType() const
    {
        return SE_CLS_DRM_RESPONSIBLE_PARTY;
    }

};

} // namespace sedris

#endif // _seDRMResponsibleParty_h
