// xxxSE_PropertyDataValueToUint8SEDRISSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8LevelSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8ReadSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8APISE_PropertyDataValueToUint8xxx
//
// xxxSE_PropertyDataValueToUint8ProducedSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8bySE_PropertyDataValueToUint8xxx: xxxSE_PropertyDataValueToUint8TheSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRISSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TeamSE_PropertyDataValueToUint8xxx
//
// xxxSE_PropertyDataValueToUint8FILESE_PropertyDataValueToUint8xxx:        xxxSE_PropertyDataValueToUint8se_listsSE_PropertyDataValueToUint8xxx.xxxSE_PropertyDataValueToUint8inlSE_PropertyDataValueToUint8xxx
//
// xxxSE_PropertyDataValueToUint8PROGRAMMERSSE_PropertyDataValueToUint8xxx: xxxSE_PropertyDataValueToUint8RobertSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8DSE_PropertyDataValueToUint8xxx'xxxSE_PropertyDataValueToUint8UrsoSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8SAICSE_PropertyDataValueToUint8xxx), xxxSE_PropertyDataValueToUint8HowardSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8LuSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8SAICSE_PropertyDataValueToUint8xxx), xxxSE_PropertyDataValueToUint8BillSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8HoranSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8SAICSE_PropertyDataValueToUint8xxx)
//
// xxxSE_PropertyDataValueToUint8DESCRIPTIONSE_PropertyDataValueToUint8xxx: xxxSE_PropertyDataValueToUint8SourceSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8codeSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8theSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8longerSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8inlineSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8methodsSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8forSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8theSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8singlySE_PropertyDataValueToUint8xxx
//              xxxSE_PropertyDataValueToUint8linkedSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8listSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8andSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8iteratorSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8codeSE_PropertyDataValueToUint8xxx
//
// SEDRIS SDK Release 4.1.4 - July 1, 2011

/*
 *                             NOTICE
 * 
 * This software is provided openly and freely for use in representing and
 * interchanging environmental data & databases.
 * 
 * This software was developed for use by the United States Government with
 * unlimited rights.  The software was developed under contract
 * DASG60-02-D-0006 TO-193 by Science Applications International Corporation.
 * The software is unclassified and is deemed as Distribution A, approved
 * for Public Release.
 * 
 * Use by others is permitted only upon the ACCEPTANCE OF THE TERMS AND
 * CONDITIONS, AS STIPULATED UNDER THE FOLLOWING PROVISIONS:
 * 
 *    1. Recipient may make unlimited copies of this software and give
 *       copies to other persons or entities as long as the copies contain
 *       this NOTICE, and as long as the same copyright notices that
 *       appear on, or in, this software remain.
 * 
 *    2. Trademarks. All trademarks belong to their respective trademark
 *       holders.  Third-Party applications/software/information are
 *       copyrighted by their respective owners.
 * 
 *    3. Recipient agrees to forfeit all intellectual property and
 *       ownership rights for any version created from the modification
 *       or adaptation of this software, including versions created from
 *       the translation and/or reverse engineering of the software design.
 * 
 *    4. Transfer.  Recipient may not sell, rent, lease, or sublicense
 *       this software.  Recipient may, however enable another person
 *       or entity the rights to use this software, provided that this
 *       AGREEMENT and NOTICE is furnished along with the software and
 *       /or software system utilizing this software.
 * 
 *       All revisions, modifications, created by the Recipient, to this
 *       software and/or related technical data shall be forwarded by the
 *       Recipient to the Government at the following address:
 * 
 *         SMDC
 *         Attention SEDRIS (TO193) TPOC
 *         P.O. Box 1500
 *         Huntsville, AL  35807-3801
 * 
 *         or via electronic mail to:  se-mgmt@sedris.org
 * 
 *    5. No Warranty. This software is being delivered to you AS IS
 *       and there is no warranty, EXPRESS or IMPLIED, as to its use
 *       or performance.
 * 
 *       The RECIPIENT ASSUMES ALL RISKS, KNOWN AND UNKNOWN, OF USING
 *       THIS SOFTWARE.  The DEVELOPER EXPRESSLY DISCLAIMS, and the
 *       RECIPIENT WAIVES, ANY and ALL PERFORMANCE OR RESULTS YOU MAY
 *       OBTAIN BY USING THIS SOFTWARE OR DOCUMENTATION.  THERE IS
 *       NO WARRANTY, EXPRESS OR, IMPLIED, AS TO NON-INFRINGEMENT OF
 *       THIRD PARTY RIGHTS, MERCHANTABILITY, OR FITNESS FOR ANY
 *       PARTICULAR PURPOSE.  IN NO EVENT WILL THE DEVELOPER, THE
 *       UNITED STATES GOVERNMENT OR ANYONE ELSE ASSOCIATED WITH THE
 *       DEVELOPMENT OF THIS SOFTWARE BE HELD LIABLE FOR ANY CONSEQUENTIAL,
 *       INCIDENTAL OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS
 *       OR LOST SAVINGS WHATSOEVER.
 */

/*
 * COPYRIGHT 2011, SCIENCE APPLICATIONS INTERNATIONAL CORPORATION.
 *                 ALL RIGHTS RESERVED.
 */

#xxxSE_PropertyDataValueToUint8ifndefSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8_SE_LISTS_INL_INCLUDEDSE_PropertyDataValueToUint8xxx
#xxxSE_PropertyDataValueToUint8defineSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8_SE_LISTS_INL_INCLUDEDSE_PropertyDataValueToUint8xxx

#xxxSE_PropertyDataValueToUint8ifndefSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8_WIN32SE_PropertyDataValueToUint8xxx    /* xxxSE_PropertyDataValueToUint8WIN32SE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8platformsSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8needSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8toSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8dllimportSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8variablesSE_PropertyDataValueToUint8xxx */
#xxxSE_PropertyDataValueToUint8defineSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8DECLSPECSE_PropertyDataValueToUint8xxx
#xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx
#xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8definedSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8SE_TURN_OFF_SUPPORT_WIN32_IMPORTSE_PropertyDataValueToUint8xxx) || xxxSE_PropertyDataValueToUint8definedSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8_MAKE_WIN32_STATICSE_PropertyDataValueToUint8xxx)
       /* xxxSE_PropertyDataValueToUint8exportingSE_PropertyDataValueToUint8xxx, xxxSE_PropertyDataValueToUint8soSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8noSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8dllSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8importSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8neededSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8hereSE_PropertyDataValueToUint8xxx */
#xxxSE_PropertyDataValueToUint8defineSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8DECLSPECSE_PropertyDataValueToUint8xxx
#xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx
#xxxSE_PropertyDataValueToUint8defineSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8DECLSPECSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8__declspecSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8dllimportSE_PropertyDataValueToUint8xxx) /* xxxSE_PropertyDataValueToUint8importingSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8aSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8variableSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8fromSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8aSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8dllSE_PropertyDataValueToUint8xxx */
#xxxSE_PropertyDataValueToUint8endifSE_PropertyDataValueToUint8xxx
#xxxSE_PropertyDataValueToUint8endifSE_PropertyDataValueToUint8xxx

xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8classSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>
xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_ListSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>::xxxSE_PropertyDataValueToUint8removeFirstSE_PropertyDataValueToUint8xxx()
{
    xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx;
    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx)
    {
        xxxSE_PropertyDataValueToUint8fprintfSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8stderrSE_PropertyDataValueToUint8xxx,"xxxSE_PropertyDataValueToUint8FatalSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8ErrorSE_PropertyDataValueToUint8xxx - xxxSE_PropertyDataValueToUint8removeFirstSE_PropertyDataValueToUint8xxx() xxxSE_PropertyDataValueToUint8ofSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8emptySE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8listSE_PropertyDataValueToUint8xxx\xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx");
        xxxSE_PropertyDataValueToUint8abortSE_PropertyDataValueToUint8xxx();
    }
    xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx
    {
        xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();
        xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8get_elem_valueSE_PropertyDataValueToUint8xxx();
        xxxSE_PropertyDataValueToUint8deleteSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx;
        xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx;
        xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx--;
        xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx) xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8NULLSE_PropertyDataValueToUint8xxx;
    }

    xxxSE_PropertyDataValueToUint8returnSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx;
}

xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8classSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>
xxxSE_PropertyDataValueToUint8constSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx& xxxSE_PropertyDataValueToUint8SEDRIS_ListSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>::xxxSE_PropertyDataValueToUint8itemSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8longSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx) xxxSE_PropertyDataValueToUint8constSE_PropertyDataValueToUint8xxx
{
    xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx;

    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx < xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx || xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx)
    {
        xxxSE_PropertyDataValueToUint8fprintfSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8stderrSE_PropertyDataValueToUint8xxx,"xxxSE_PropertyDataValueToUint8FatalSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8ErrorSE_PropertyDataValueToUint8xxx - xxxSE_PropertyDataValueToUint8askedSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8forSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8itemSE_PropertyDataValueToUint8xxx %xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8ofSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8aSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8listSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8withSE_PropertyDataValueToUint8xxx " \
                "xxxSE_PropertyDataValueToUint8onlySE_PropertyDataValueToUint8xxx % xxxSE_PropertyDataValueToUint8itemsSE_PropertyDataValueToUint8xxx\xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx", (xxxSE_PropertyDataValueToUint8intSE_PropertyDataValueToUint8xxx) xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx, (xxxSE_PropertyDataValueToUint8intSE_PropertyDataValueToUint8xxx) xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx);
        xxxSE_PropertyDataValueToUint8abortSE_PropertyDataValueToUint8xxx();
    }

    xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx;

    xxxSE_PropertyDataValueToUint8forSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8intSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx=xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx; xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx; xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx++)
        xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();

    xxxSE_PropertyDataValueToUint8returnSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8get_elem_valueSE_PropertyDataValueToUint8xxx();
}

xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8classSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>
xxxSE_PropertyDataValueToUint8voidSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_ListSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>::xxxSE_PropertyDataValueToUint8removeItemSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8longSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx)
{
    xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx, *xxxSE_PropertyDataValueToUint8prevSE_PropertyDataValueToUint8xxx;

    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx < xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx || xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx)
    {
        xxxSE_PropertyDataValueToUint8fprintfSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8stderrSE_PropertyDataValueToUint8xxx,"xxxSE_PropertyDataValueToUint8FatalSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8ErrorSE_PropertyDataValueToUint8xxx - xxxSE_PropertyDataValueToUint8askedSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8toSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8removeSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8itemSE_PropertyDataValueToUint8xxx %xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8ofSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8aSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8listSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8withSE_PropertyDataValueToUint8xxx " \
                "xxxSE_PropertyDataValueToUint8onlySE_PropertyDataValueToUint8xxx % xxxSE_PropertyDataValueToUint8itemsSE_PropertyDataValueToUint8xxx\xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx", (xxxSE_PropertyDataValueToUint8intSE_PropertyDataValueToUint8xxx) xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx, (xxxSE_PropertyDataValueToUint8intSE_PropertyDataValueToUint8xxx) xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx);
        xxxSE_PropertyDataValueToUint8abortSE_PropertyDataValueToUint8xxx();
    }

    xxxSE_PropertyDataValueToUint8prevSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8NULLSE_PropertyDataValueToUint8xxx;
    xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx  = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx;

    xxxSE_PropertyDataValueToUint8forSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8intSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx=xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx; xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx; xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx++)
    {
        xxxSE_PropertyDataValueToUint8prevSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx;
        xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx  = xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();
    }

    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8prevSE_PropertyDataValueToUint8xxx)
        xxxSE_PropertyDataValueToUint8prevSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8set_next_elemSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx());
    xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx // xxxSE_PropertyDataValueToUint8sinceSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8prevSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint8NULLSE_PropertyDataValueToUint8xxx, xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx
        xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();

    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx)
        xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8prevSE_PropertyDataValueToUint8xxx;

    xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx--;

    xxxSE_PropertyDataValueToUint8deleteSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx;
}

xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8classSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>
xxxSE_PropertyDataValueToUint8voidSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_ListSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>::xxxSE_PropertyDataValueToUint8addFirstSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8constSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx& xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx)
{
    xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8newSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>(xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx);

    xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8set_next_elemSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx);

    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (!xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx)
    {
        xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx;
    }
    xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx
    {
        xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx;
    }

    xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx++;
}

xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8classSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>
xxxSE_PropertyDataValueToUint8voidSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_ListSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>::xxxSE_PropertyDataValueToUint8addLastSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8constSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx& xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx)
{
    xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8newSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>(xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx);

    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx)
    {
        xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8set_next_elemSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx);
        xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();
    }
    xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx
    {
        xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx;
    }
    xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx++;
}

xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8classSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>
xxxSE_PropertyDataValueToUint8voidSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_ListSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>::xxxSE_PropertyDataValueToUint8addAfterSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8longSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx, xxxSE_PropertyDataValueToUint8constSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx& xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx)
{

    xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx < xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx)
          xxxSE_PropertyDataValueToUint8addFirstSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx);
    xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8ifSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx <= xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx || xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx == xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx)
        xxxSE_PropertyDataValueToUint8addLastSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx);
    xxxSE_PropertyDataValueToUint8elseSE_PropertyDataValueToUint8xxx
      {
          xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8newSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>(xxxSE_PropertyDataValueToUint8elemSE_PropertyDataValueToUint8xxx);
          xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx, *xxxSE_PropertyDataValueToUint8holdSE_PropertyDataValueToUint8xxx;

          xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx  = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx;
          xxxSE_PropertyDataValueToUint8forSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8intSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx=xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx; xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8nSE_PropertyDataValueToUint8xxx; xxxSE_PropertyDataValueToUint8iSE_PropertyDataValueToUint8xxx++)
            xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx  = xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();

          xxxSE_PropertyDataValueToUint8holdSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();
          xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8set_next_elemSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx);
          xxxSE_PropertyDataValueToUint8new_elemSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8set_next_elemSE_PropertyDataValueToUint8xxx(xxxSE_PropertyDataValueToUint8holdSE_PropertyDataValueToUint8xxx);

          xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx++;
      }
}

xxxSE_PropertyDataValueToUint8templateSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8classSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>
xxxSE_PropertyDataValueToUint8voidSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8SEDRIS_ListSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx>::xxxSE_PropertyDataValueToUint8removeAllSE_PropertyDataValueToUint8xxx()
{
    xxxSE_PropertyDataValueToUint8SEDRIS_List_ElemSE_PropertyDataValueToUint8xxx<xxxSE_PropertyDataValueToUint8TSE_PropertyDataValueToUint8xxx> *xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx;
    xxxSE_PropertyDataValueToUint8whileSE_PropertyDataValueToUint8xxx (xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx)
    {
        xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx  = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx;
        xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx->xxxSE_PropertyDataValueToUint8next_elemSE_PropertyDataValueToUint8xxx();
        xxxSE_PropertyDataValueToUint8deleteSE_PropertyDataValueToUint8xxx xxxSE_PropertyDataValueToUint8tmpSE_PropertyDataValueToUint8xxx;
    }
    xxxSE_PropertyDataValueToUint8populationSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint80SE_PropertyDataValueToUint8xxx;
    xxxSE_PropertyDataValueToUint8tailSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8headSE_PropertyDataValueToUint8xxx = xxxSE_PropertyDataValueToUint8NULLSE_PropertyDataValueToUint8xxx;
}

#xxxSE_PropertyDataValueToUint8endifSE_PropertyDataValueToUint8xxx // xxxSE_PropertyDataValueToUint8_SE_LISTS_INL_INCLUDEDSE_PropertyDataValueToUint8xxx
